
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";




export const metadata = {
  title: "BISFLIX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
