
"use client";

import "./globals.css";
import Header from "../components/shared/Navbar/Header.jsx";
import Footer from "../components/shared/Footer/Footer.jsx";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Provider } from 'react-redux';
import store from '../redux/store';



// export const metadata = {
//   title: "BISFLIX",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </Provider>
  );
}
